version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=pass1
      - POSTGRES_DB=db1
    ports:
      - 5432:5432
  app:
    build:
      context: .
      args:
        VARIANT: 18-bullseye
    environment:
      - DB_URI=postgresql://user1:pass1@db:5432/db1
    user: node
    volumes:
      - ~/.ssh:/home/node/.ssh
      - ../:/workspaces/app
    command: /bin/sh -c "while sleep infinity; do :; done"
    links:
      - db
